version: "3.5"
services:
  web-client-dev-env:
    image: mondial-web-client
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mondial
    ports:
      - "4200:4200"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
networks:
  mondial:
    name: mondial
